# falcon colorscheme for alacritty

# Default colors
[colors.primary]
background = '#020221'
foreground = '#b4b4b9'

[colors.cursor]
text = '#020221'
cursor = '#ffe8c0'

# Normal colors
[colors.normal]
black   = '#000004'
red     = '#ff3600'
green   = '#ff761a'
yellow  = '#ffc552'
blue    = '#bfdaff'
magenta = '#ff761a'
cyan    = '#ffc552'
white   = '#b4b4b9'

# Bright colors
[colors.bright]
black   = '#787882'
red     = '#ff8e78'
green   = '#ffb07b'
yellow  = '#ffd392'
blue    = '#bfdaff'
magenta = '#ffb07b'
cyan    = '#ffd392'
white   = '#f8f8ff'
